name: .NET Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: Food_to_go

    - name: Build
      run: dotnet build
      working-directory: Food_to_go

    - name: Test
      run: dotnet test
      working-directory: Food_to_go
